export const LOAD_CASES = 'LOAD_CASES';
export const LOAD_PREFIXES = 'LOAD_PREFIXES';
export const LOAD_PREFIXGRPS = 'LOAD_PREFIXGRPS';
export const LOAD_PATHOLOGISTS = 'LOAD_PATHOLOGISTS';
export const LOAD_RESIDENTS = 'LOAD_RESIDENTS';
